export const Role = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  DEPARTMENT_ADMIN: 'DEPARTMENT_ADMIN',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  RECEPTIONIST: 'RECEPTIONIST',
  RESOURCE_MANAGER: 'RESOURCE_MANAGER',
  PATIENT: 'PATIENT',
} as const;

export type RoleType = keyof typeof Role;

export const BedType = {
  ICU: 'ICU',
  GENERAL: 'GENERAL',
  EMERGENCY: 'EMERGENCY',
  ISOLATION: 'ISOLATION',
} as const;

export const BedStatus = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  OCCUPIED: 'OCCUPIED',
  MAINTENANCE: 'MAINTENANCE',
} as const;

export const EquipmentStatus = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  IN_USE: 'IN_USE',
  MAINTENANCE: 'MAINTENANCE',
} as const;

export const CalibrationStatus = {
  CALIBRATED: 'CALIBRATED',
  DUE_SOON: 'DUE_SOON',
  OVERDUE: 'OVERDUE',
  MAINTENANCE_REQUIRED: 'MAINTENANCE_REQUIRED',
} as const;

export const OTStatus = {
  AVAILABLE: 'AVAILABLE',
  SCHEDULED: 'SCHEDULED',
  RESERVED: 'RESERVED',
  IN_USE: 'IN_USE',
  MAINTENANCE: 'MAINTENANCE',
} as const;

export const AppointmentStatus = {
  SCHEDULED: 'SCHEDULED',
  CHECKED_IN: 'CHECKED_IN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const AdmissionStatus = {
  ADMITTED: 'ADMITTED',
  TRANSFERRED: 'TRANSFERRED',
  DISCHARGED: 'DISCHARGED',
  CANCELLED: 'CANCELLED',
} as const;

export const TransactionType = {
  BED_ALLOCATION: 'BED_ALLOCATION',
  DOCTOR_ASSIGNMENT: 'DOCTOR_ASSIGNMENT',
  EQUIPMENT_RESERVATION: 'EQUIPMENT_RESERVATION',
  OT_BOOKING: 'OT_BOOKING',
  PATIENT_ADMISSION: 'PATIENT_ADMISSION',
  PATIENT_TRANSFER: 'PATIENT_TRANSFER',
  MULTI_RESOURCE_ADMISSION: 'MULTI_RESOURCE_ADMISSION',
} as const;

export const TransactionPriority = {
  EMERGENCY: 'EMERGENCY',
  CRITICAL: 'CRITICAL',
  URGENT: 'URGENT',
  ROUTINE: 'ROUTINE',
} as const;

export type TransactionPriorityType = keyof typeof TransactionPriority;

export const TransactionStatus = {
  REQUESTED: 'REQUESTED',
  VALIDATING: 'VALIDATING',
  PROCESSING: 'PROCESSING',
  RESERVED: 'RESERVED',
  COMMITTED: 'COMMITTED',
  FAILED: 'FAILED',
  COMPENSATING: 'COMPENSATING',
  ROLLED_BACK: 'ROLLED_BACK',
  ESCALATED: 'ESCALATED',
  CANCELLED: 'CANCELLED',
} as const;

export const ResourceType = {
  BED: 'BED',
  DOCTOR: 'DOCTOR',
  EQUIPMENT: 'EQUIPMENT',
  OT: 'OT',
} as const;

export const EventType = {
  RESOURCE_REQUESTED: 'RESOURCE_REQUESTED',
  RESOURCE_LOCK_ACQUIRED: 'RESOURCE_LOCK_ACQUIRED',
  RESOURCE_RESERVED: 'RESOURCE_RESERVED',
  DOCTOR_ASSIGNED: 'DOCTOR_ASSIGNED',
  EQUIPMENT_ASSIGNED: 'EQUIPMENT_ASSIGNED',
  COMMITTED: 'COMMITTED',
  RESOURCE_FAILED: 'RESOURCE_FAILED',
  COMPENSATION_STARTED: 'COMPENSATION_STARTED',
  RESOURCE_RELEASED: 'RESOURCE_RELEASED',
  ROLLED_BACK: 'ROLLED_BACK',
  ESCALATED: 'ESCALATED',
} as const;

export const EventStatus = {
  PENDING: 'PENDING',
  PROCESSED: 'PROCESSED',
  DUPLICATE: 'DUPLICATE',
  REJECTED: 'REJECTED',
  OUT_OF_ORDER: 'OUT_OF_ORDER',
} as const;

export const ConflictStatus = {
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
  OVERRIDDEN: 'OVERRIDDEN',
  ESCALATED: 'ESCALATED',
} as const;
